### ISSUE TITLE
MY Issue : These cards are misaligned  .

### ISSUE THREAD

**Issue by Amanrk7** [EddieHubCommunity/EddieHubCommunity.github.io#204] opened 2021-09-13 16:37 UTC
![image](https://user-images.githubusercontent.com/85789009/133122389-91d2589e-b75a-43da-9ffd-3ed0c86b744b.png)
[](url)

and by correcting with the inspect section  the image is shown as  i set the width to 49px  :- 
![image](https://user-images.githubusercontent.com/85789009/133122811-192a8497-94ce-4e8d-aa96-27916dae23ac.png)

It will be great to get the response from you .

**Comment by Amanrk7** [comment] 2021-09-13 16:41
not 49px , 49%{width}

**Comment by Panquesito7** [comment] 2021-09-13 17:28
Once another staff is added to the list it will look totally fine, I think. 🙂

**Comment by SaraJaoude** [comment] 2021-09-14 09:29
Thank you but this is a duplicate of:

https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/170

**Closed by SaraJaoude** 2021-09-14 09:29 UTC

**Comment by Amanrk7** [comment] 2021-09-14 09:42
hi , yes u are right i also saw that but after that also it was misaligned {this time in the section of  "Kaiwalya Koparkar"} , so when i set the width to 49% , it was good in shape . But fine if u had resolved it already , maybe it was not showing the repair in my browser. but it was really great contributing in it .
i'll try , my best next time .  Tip from your side will be a great help .

**Comment by eddiejaoude** [comment] 2021-09-14 10:06
Thank you for raising the issue and experimenting with solutions. Please feel free to add it to the existing issue #170 as it is not fixed yet
