### ISSUE TITLE
Moderators div are not aligned properly

### ISSUE THREAD

**Issue by WebShivam** [EddieHubCommunity/EddieHubCommunity.github.io#184] opened 2021-06-04 17:02 UTC
Here is the screenshot 👇 
![eddie-mod-section](https://user-images.githubusercontent.com/64413107/120836511-455c5a00-c583-11eb-8b14-89b87f8a8bea.jpg)

**Comment by adityaraute** [comment] 2021-07-21 09:39
Because Alexander's name is on two lines. Something surely needs to be done. But that will increase the height of all cards in the second row, so inconsistencies galore.

**Comment by eddiejaoude** [comment] 2021-09-14 09:30
> inconsistencies galore

@adityaraute this is not collaborative language, I would have expected more from you 😞

**Comment by SaraJaoude** [comment] 2021-09-14 09:33
This is a duplicate of:
https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/170

**Closed by SaraJaoude** 2021-09-14 09:33 UTC
